name: Update Sketch Library from JSON file

on:
  push:
    paths:
      - colors.json
      - .github/workflows/**.yml
    branches: [main]
  pull_request:
    paths:
      - colors.json
      - .github/workflows/**.yml
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Update Sketch Library
        run: yarn start
      - name: Push changes in Sketch Library
        uses: actions-x/commit@v2
        with:
          email: developer@sketch.com
          name: Sketch Developer
          files: color-library.sketch
